export const walletConstants = {
  CONNECT_SUCCESS: 'WALLET_CONNECT_SUCCESS',
  CONNECT_ERROR: 'WALLET_CONNECT_ERROR',
  TRANSACTION_SUCCESS: 'WALLET_TRANSACTION_SUCCESS',
  TRANSACTION_ERROR: 'WALLET_TRANSACTION_ERROR',
  SHOW_CONNECTION_ALERT: 'SHOW_CONNECTION_ALERT'
}
